"""init

Revision ID: c767713ec998
Revises: 
Create Date: 2023-03-20 22:09:35.239218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c767713ec998"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_category_id"), "category", ["id"], unique=False)
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    op.create_table(
        "family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_family_id"), "family", ["id"], unique=False)
    op.create_index(op.f("ix_family_name"), "family", ["name"], unique=True)
    op.create_table(
        "transaction_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_target_id"), "transaction_target", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_target_name"), "transaction_target", ["name"], unique=True
    )
    op.create_table(
        "unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ratio", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unit_id"), "unit", ["id"], unique=False)
    op.create_index(op.f("ix_unit_name"), "unit", ["name"], unique=True)
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_family_id"), "account", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=False)
    op.create_index(op.f("ix_account_name"), "account", ["name"], unique=True)
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("transaction_target_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_target_id"],
            ["transaction_target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_category_id"), "item", ["category_id"], unique=False)
    op.create_index(op.f("ix_item_id"), "item", ["id"], unique=False)
    op.create_index(op.f("ix_item_name"), "item", ["name"], unique=True)
    op.create_index(
        op.f("ix_item_transaction_target_id"),
        "item",
        ["transaction_target_id"],
        unique=False,
    )
    op.create_index(op.f("ix_item_unit_id"), "item", ["unit_id"], unique=False)
    op.create_table(
        "payment_method",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("tax_deduction_rate", sa.Double(), nullable=True),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_method_family_id"),
        "payment_method",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_method_id"), "payment_method", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_method_name"), "payment_method", ["name"], unique=True
    )
    op.create_table(
        "price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_id"), "price", ["id"], unique=False)
    op.create_index(op.f("ix_price_item_id"), "price", ["item_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_method.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transaction_id"), "transaction", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_price_item_id"), table_name="price")
    op.drop_index(op.f("ix_price_id"), table_name="price")
    op.drop_table("price")
    op.drop_index(op.f("ix_payment_method_name"), table_name="payment_method")
    op.drop_index(op.f("ix_payment_method_id"), table_name="payment_method")
    op.drop_index(op.f("ix_payment_method_family_id"), table_name="payment_method")
    op.drop_table("payment_method")
    op.drop_index(op.f("ix_item_unit_id"), table_name="item")
    op.drop_index(op.f("ix_item_transaction_target_id"), table_name="item")
    op.drop_index(op.f("ix_item_name"), table_name="item")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_index(op.f("ix_item_category_id"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_account_name"), table_name="account")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_index(op.f("ix_account_family_id"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_unit_name"), table_name="unit")
    op.drop_index(op.f("ix_unit_id"), table_name="unit")
    op.drop_table("unit")
    op.drop_index(op.f("ix_transaction_target_name"), table_name="transaction_target")
    op.drop_index(op.f("ix_transaction_target_id"), table_name="transaction_target")
    op.drop_table("transaction_target")
    op.drop_index(op.f("ix_family_name"), table_name="family")
    op.drop_index(op.f("ix_family_id"), table_name="family")
    op.drop_table("family")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_index(op.f("ix_category_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
